src/webcrawler/grails-app/domain/model/v2/Alert.groovy
package model.v2

class Alert {

    String termino

    static constraints = {
    }
}

src/webcrawler/grails-app/controllers/model/v2/AlertController.groovy
package model.v2

import grails.plugin.springsecurity.annotation.Secured
import grails.transaction.Transactional

@Secured("ROLE_ADMIN")
class AlertController {

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        params.offset = params.offset ?: 0

        def criteria = Alert.createCriteria()
        def query = criteria.list {
            maxResults(new Integer(params.max))
            firstResult(new Integer(params.offset))
        }

        if (params.message)
            flash.error = params.message

        respond query, model: [totalCount: Alert.count()]
    }

    def create(){
        def termino =  params.termino
        if(termino){
            Alert alert = new Alert(termino: termino)
            alert.save()
            flash.message = "Alert Saved"
        }else{
            flash.error = "Missing Params"
        }
        redirect(action: 'index')
    }

    @Transactional
    def delete(Integer id){
        Alert alert = Alert.get(id)
        if(alert){
            alert.delete()
            flash.message = "Alert Deleted"
        }else{
            flash.error = "Alert Not Found"
        }
        redirect(action: 'index')
    }
}

src/webcrawler/grails-app/views/alert/index.gsp
<%@ page import="model.v2.Alert" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="admin">
    <title>Alertas</title>
</head>

<body>
<div class="row">
    <div class="col-lg-6">
        <div class="card">
            <div class="card-header">
                <i class="fa fa-align-justify"></i> Nueva Alerta
            </div>

            <div class="card-body">
                <g:form url='[controller: "alert", action: "create"]' method="get" >
                    <div class="input-group">
                            <input type="text" name="termino" class="form-control" placeholder="Type your new Alert">
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-primary">
                                    <i class="fa fa-send"></i>
                                    Submit
                                </button>
                            </span>
                    </g:form>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-6">
        <div class="card">
            <div class="card-header">
                <i class="fa fa-align-justify"></i> Alertas
            </div>

            <div class="card-body">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Termino de Alerta</th>
                    </tr>
                    </thead>
                    <tbody>
                    <g:each in="${alertInstanceList}" var="entity">
                        <tr>
                            <td>${entity.termino.size() > 20 ? entity.termino.substring(0, 20) + " ..." : entity.termino}</td>
                            <td>
                                <a href="${createLink(controller: 'alert', action: 'delete', id: entity.id)}" class="btn btn-danger">
                                    <i class="fa fa-remove"></i> Remove
                                </a>
                            </td>
                        </tr>
                    </g:each>
                    </tbody>
                </table>

                <div class="pagination">
                    <g:paginate total="${totalCount ?: 0}"/>
                </div>
            </div>
        </div>
    </div>
    <!--/.col-->
</div>
<!--/.row-->

</body>
</html>