src/webcrawler/grails-app/domain/model/v2/Category.groovy
package model.v2

import com.google.gson.annotations.SerializedName

class Category {

    String nivel1
    String idRubro
    @SerializedName("PrimerNivel")
    String primerNivel
    @SerializedName("Total")
    String total

    //Extra Data
    Date lastUpdated
    boolean enabled = false

    static constraints = {
        primerNivel unique: true
    }

    def updateModel(Category item) {
        this.nivel1 = item.nivel1
        this.idRubro = item.idRubro
        this.primerNivel = item.primerNivel
        this.total = item.total
        save()
    }

    int countBidToday() {
        Date today = new Date().clearTime()
        Date todayEnd = today + 1
        def query = Act.withCriteria() {
            eq("category", this)
//            eq("processed", true)
            lt("dateCreated", todayEnd)
            ge("dateCreated", today)
            projections {
                count "id", 'mycount'
            }
        }
        return query[0]
    }

    int countBidTotal() {
        def query = Act.withCriteria() {
            eq("category", this)
//            eq("processed", true)
            projections {
                count "id", 'mycount'
            }
        }
        return query[0]
    }
}

src/webcrawler/grails-app/controllers/model/v2/CategoryController.groovy
package model.v2

import grails.converters.JSON
import grails.plugin.springsecurity.annotation.Secured
import grails.transaction.Transactional

class CategoryController {

    def scrapService

    @Secured(["ROLE_ADMIN", "ROLE_USER"])
    def index(Integer max) {
        //TODO Offset and Order breaking query increasing max to list them all
        params.max = Math.min(max ?: 100, 100)
        params.offset = params.offset ?: 0
        def criteria = Category.createCriteria()
        def query = criteria.list(max: params.max, offset: params.offset) {
            order("enabled", "desc")
        }

        if (params.message)
            flash.error = params.message

        respond query, model: [totalCount: Category.count()]
    }

    @Secured(["ROLE_ADMIN"])
    def categoryRefresh() {
        scrapService.fetchCategories()
        flash.message = "Category Refresh started this may take a while!"
        redirect(action: 'index')
    }

    @Secured(["ROLE_ADMIN"])
    @Transactional
    def enableCategoria(int id) {
        Category categoryV2 = Category.findById(id)
        def map = [:]

        if (categoryV2) {
            categoryV2.enabled = true
            categoryV2.save(flush: true)
            map.message = "category enabled"
        } else {
            response.status = 404
            map.error = "category not found"
        }

        render map as JSON
    }

    @Secured(["ROLE_ADMIN"])
    @Transactional
    def disableCategoria(int id) {
        Category categoryV2 = Category.findById(id)
        def map = [:]

        if (categoryV2) {
            categoryV2.enabled = false
            categoryV2.save(flush: true)
            map.message = "category disabled"
        } else {
            response.status = 404
            map.error = "category not found"
        }

        render map as JSON
    }

}

src/webcrawler/grails-app/views/category/index.gsp
<%@ page import="model.v2.Category" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="admin">
    <title>Categories</title>
</head>

<body>
<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <i class="fa fa-align-justify"></i> Oportunidades de negocio
                <sec:ifAllGranted roles="ROLE_ADMIN">
                <a href="${createLink(controller: 'category', action: 'categoryRefresh')}" type="button"
                   class="btn btn-outline-danger pull-right" style="margin-top: 1px;">
                    <i class="fa fa-refresh"></i>&nbsp; Refresh
                </a>
                </sec:ifAllGranted>
            </div>

            <div class="card-body">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Enabled</th>
                        <th>nivel1</th>
                        <th>PrimerNivel</th>
                        <th>Total</th>
                        <th>Today</th>
                    </tr>
                    </thead>
                    <tbody>
                    <g:each in="${categoryInstanceList}" var="entity">
                        <tr>
                            <td>
                                <label class="switch switch-3d switch-primary">
                                    <input type="checkbox" class="switch-input enable-cat"
                                           data-id="${entity.id}" ${entity.isEnabled() ? 'checked' : ''}>
                                    <span class="switch-label"></span>
                                    <span class="switch-handle"></span>
                                </label>
                            </td>
                            <td><a href="${createLink(controller: 'bidding', action: "index", id: entity.id)}" >${entity.nivel1}</a></td>
                            <td>${entity.primerNivel}</td>
                            <td>${entity.countBidTotal()}</td>
                            <td>${entity.countBidToday()}</td>
                        </tr>
                    </g:each>
                    </tbody>
                </table>

                <div class="pagination">
                    <g:paginate total="${totalCount ?: 0}"/>
                </div>
            </div>
        </div>
    </div>
    <!--/.col-->
</div>
<!--/.row-->


<g:javascript>
    $(function () {

        $('.switch-input').change(function () {

            var elem = $(this);
            var url = "";
            var idCat = elem.attr("data-id");
            if(elem.prop('checked')){
                url = "${createLink(controller: 'category', action: 'enableCategoria')}/";
            }else{
                url = "${createLink(controller: 'category', action: 'disableCategoria')}/";
            }



            $.ajax({
                url: url + idCat,
                headers: {
                    Accept: "application/json; charset=utf-8",
                    "Content-Type": "application/json; charset=utf-8"
                }
            }).done(function (data) {
                // check connection
                toastr.success(data.message);
            }).fail(function( data, textStatus, errorThrown ) {
                toastr.error(data.responseJSON.error);
                elem.prop('checked', !elem.prop('checked'));
            });
        });

    });

</g:javascript>

</body>
</html>