src/webcrawler/grails-app/domain/model/v2/Contact.groovy
package model.v2

class Contact {

    String name
    String email

    static constraints = {
        email email: true
    }
}

src/webcrawler/grails-app/controllers/model/v2/ContactController.groovy
package model.v2

import grails.plugin.springsecurity.annotation.Secured
import grails.transaction.Transactional

@Secured("ROLE_ADMIN")
class ContactController {

    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        params.offset = params.offset ?: 0

        def criteria = Contact.createCriteria()
        def query = criteria.list {
            maxResults(new Integer(params.max))
            firstResult(new Integer(params.offset))
        }

        if (params.message)
            flash.error = params.message

        respond query, model: [totalCount: Contact.count()]
    }

    def create() {
        def email = params.email
        def name = params.name
        if (email) {
            Contact Contact = new Contact(email: email, name: name)
            Contact.save()
            flash.message = "Contact Saved"
        } else {
            flash.error = "Missing Params"
        }
        redirect(action: 'index')
    }

    @Transactional
    def delete(Integer id) {
        Contact Contact = Contact.get(id)
        if (Contact) {
            Contact.delete()
            flash.message = "Contact Deleted"
        } else {
            flash.error = "Contact Not Found"
        }
        redirect(action: 'index')
    }
}

src/webcrawler/grails-app/views/contact/index.gsp
<%@ page import="model.v2.Contact" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="admin">
    <title>Contactos</title>
</head>

<body>
<div class="row">
    <div class="col-lg-6">
        <div class="card">
            <div class="card-header">
                <i class="fa fa-align-justify"></i> Agregar Contacto
            </div>

            <div class="card-body">
                <g:form url='[controller: "contact", action: "create"]' method="get" >
                    <div class="input-group">
                            <input type="text" name="email" class="form-control" placeholder="Email">
                            <input type="text" name="name" class="form-control" placeholder="Person Name">
                            <span class="input-group-btn">
                                <button type="submit" class="btn btn-primary">
                                    <i class="fa fa-send"></i>
                                    Submit
                                </button>
                            </span>
                    </g:form>
                </div>
            </div>
        </div>
    </div>

    <div class="col-lg-6">
        <div class="card">
            <div class="card-header">
                <i class="fa fa-align-justify"></i> Contactos
            </div>

            <div class="card-body">
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Email</th>
                        <th>Name</th>
                    </tr>
                    </thead>
                    <tbody>
                    <g:each in="${contactInstanceList}" var="entity">
                        <tr>
                            <td>${entity.email}</td>
                            <td>${entity.name}</td>
                            <td>
                                <a href="${createLink(controller: 'contact', action: 'delete', id: entity.id)}" class="btn btn-danger">
                                    <i class="fa fa-remove"></i> Remove
                                </a>
                            </td>
                        </tr>
                    </g:each>
                    </tbody>
                </table>

                <div class="pagination">
                    <g:paginate total="${totalCount ?: 0}"/>
                </div>
            </div>
        </div>
    </div>
    <!--/.col-->
</div>
<!--/.row-->

</body>
</html>