src/webcrawler/grails-app/domain/model/v2/bidding/Bidding.groovy
package model.v2.bidding

import groovy.json.StringEscapeUtils
import groovy.transform.ToString
import jline.internal.Nullable
import model.v2.Alert
import model.v2.Category
import model.v2.OtherContract
import org.apache.commons.lang.StringUtils
import util.ClassUtils
import util.StringConstants
import util.domain.BaseDomain
import util.domain.DomainInterface

@ToString(includeNames = true, includeFields = true, excludes = "id, version, dateCreated, myMailProviderService, category, observada, lastUpdated, especificacionesTecnicas")
class Bidding implements DomainInterface<Bidding> {

    def myMailProviderService

    Date dateCreated
    Date lastUpdated
    @Nullable
    Category category
    @Nullable
    OtherContract otherContract
    boolean observada

    //Header
    String numero
    String descripcion
    String objetoContratacion
    //Entidad
    String entidad
    String dependencias
    String unidadDeCompra
    String direccion
    //ContactUser
    String contactUserNombre
    String contactUserCargo

    TechSpec especificacionesTecnicas

    static hasMany = [documentosAdjuntos: DocAttached, avisos: Label]

    static constraints = {
        numero unique: true
        category nullable: true
        otherContract nullable: true
    }

    static mapping = {
        numero sqlType: 'text', nullable: true
        descripcion sqlType: 'longText', nullable: true
        objetoContratacion sqlType: 'longText', nullable: true
        entidad sqlType: 'longText', nullable: true
        dependencias sqlType: 'longText', nullable: true
        unidadDeCompra sqlType: 'longText', nullable: true
        direccion sqlType: 'longText', nullable: true
        contactUserNombre sqlType: 'longText', nullable: true
        contactUserCargo sqlType: 'longText', nullable: true

        especificacionesTecnicas lazy: false
        documentosAdjuntos lazy: false
        avisos lazy: false
        category lazy: false
    }

    boolean isModelChanged(Bidding source) {
        if (!source.compare(this)) {
            def diff = []
            String json1 = getString()
            String json2 = source.getString()

            boolean docAreEqueals = BaseDomain.compare2List(documentosAdjuntos, source.documentosAdjuntos)

            boolean avisosEqueals = BaseDomain.compare2List(avisos, source.avisos)

            if (!json1.equals(json2)) {
                numero = source.numero
                descripcion = source.descripcion
                objetoContratacion = source.objetoContratacion
                entidad = source.entidad
                dependencias = source.dependencias
                unidadDeCompra = source.unidadDeCompra
                direccion = source.direccion
                contactUserNombre = source.contactUserNombre
                contactUserCargo = source.contactUserCargo
                diff << "Informacion Basica de Licitacion Actualizadas"

            }

            if (!docAreEqueals) {
                documentosAdjuntos.each {
                    it.delete()
                }
                documentosAdjuntos = source.documentosAdjuntos
                diff << "Documentos Adjuntos Actualizados"
            }

            if (!avisosEqueals) {
                avisos.each {
                    it.delete()
                }
                avisos = source.avisos
                diff << "Avisos Actualizados"
            }

            if (!especificacionesTecnicas.compare(source.especificacionesTecnicas)) {
                especificacionesTecnicas = source.especificacionesTecnicas
                diff << "Especificaciones Tecnicas Actualizadas"
            }

            println("Updating Model Difference >>>>>> " + diff)

            this.saveProcedure()
            return true
        }
        return false
    }

    void saveProcedure() {
        if (this.validate()) {
            if (especificacionesTecnicas && especificacionesTecnicas.validate())
                especificacionesTecnicas.save()
            this.save()
            println("Saving Bid >>>>>> " + this.numero)
        }
    }

    void saveValidation() {
        def biddingExits = Bidding.findByNumero(numero)
        if (biddingExits) {
            println("existing bid " + numero)
            biddingExits.isModelChanged(this)
        } else {
            saveProcedure()
        }
    }

    boolean compare(Bidding other) {
        String json1 = getString()
        String json2 = other.getString()

        boolean docAreEqueals = BaseDomain.compare2List(documentosAdjuntos, other.documentosAdjuntos)

        boolean avisosEqueals = BaseDomain.compare2List(avisos, other.avisos)

        return json1.equals(json2) && docAreEqueals && avisosEqueals && especificacionesTecnicas.compare(other.especificacionesTecnicas)
    }

    def afterInsert() {
        def wordList = Alert.getAll()
        wordList.each {
            if (StringUtils.containsIgnoreCase(descripcion, it.termino)
                    || especificacionesTecnicas.containsTerm(it.termino)) {
                myMailProviderService.insertAlert(this, it.termino)
            }
        }
    }

    def getPanamaLink() {
        return String.format(util.UrlConstants.URL_LICITACION_LINK, numero)
    }

    String getString() {
        return StringEscapeUtils.escapeJava(toString())
    }

    def getFechaPublicacion() {
        def fecha = ""
        avisos.each {
            if (it.label.contains(StringConstants.FECHA_PUBLICACION_CONST)) {
                fecha = it.value_field
            }
        }
        return fecha
    }

    def getFechaRecepcion() {
        def fecha = null
        avisos.each {
            if (it.label.contains(StringConstants.FECHA_RECEPCION_CONST)) {
                fecha = it.value_field
            }
        }
        return fecha
    }

    def getFechaPresentacion() {
        def fecha = null
        avisos.each {
            if (it.label.contains(StringConstants.FECHA_PRESENTACION_CONST)) {
                fecha = it.value_field
            }
        }
        return fecha
    }

    def cleanAllStrings(){
        ClassUtils.cleanStringFields(this)
        for(DocAttached item: documentosAdjuntos){
            ClassUtils.cleanStringFields(item)
        }
        for(Label item: avisos){
            ClassUtils.cleanStringFields(item)
        }
        ClassUtils.cleanStringFields(especificacionesTecnicas)
        for (TechSpecItem item: especificacionesTecnicas.values){
            ClassUtils.cleanStringFields(item)
            for (TechSpecItemLevel2 item2: item.values){
                ClassUtils.cleanStringFields(item2)
            }
        }
        Bidding.withTransaction {
            saveValidation()
        }
    }

}

src/webcrawler/grails-app/domain/model/v2/bidding/DocAttached.groovy
package model.v2.bidding

import com.google.gson.annotations.SerializedName
import groovy.json.StringEscapeUtils
import groovy.transform.ToString

import util.domain.DomainInterface

@ToString(includeNames = true, includeFields = true, excludes = "id,version,link")
class DocAttached implements DomainInterface<DocAttached>{

    int tipoFiltro
    //plus base URL
    String link
    String comentario
    @SerializedName("Description")
    String description
    @SerializedName("FechaCreacion")
    String fechaCreacion

    static constraints = {
    }

    static mapping = {
        link sqlType: 'longText', nullable: true
    }

    boolean compare(DocAttached other) {
        String json1 = getString()
        String json2 = other.getString()

        //Handle link updates with no report
        if(!link.equals(other.link)){
            link = other.link
            save()
        }

        return json1.equals(json2)
    }

    String getString(){
        return StringEscapeUtils.escapeJava(toString())
    }

    def getPanamaLink() {
        return util.UrlConstants.URL_BASE.concat(link)
    }

}

src/webcrawler/grails-app/domain/model/v2/bidding/Label.groovy
package model.v2.bidding

import groovy.json.StringEscapeUtils
import groovy.transform.ToString

import util.domain.DomainInterface

@ToString(includeNames = true, includeFields = true, excludes = "id,version")
class Label implements DomainInterface<Label>{

    String label
    String value_field

    static constraints = {
        value_field nullable: true
    }

    static mapping = {
        value_field sqlType: 'longText', nullable: true
    }

    boolean compare(Label other) {
        String json1 = this.getString()
        String json2 = other.getString()
        return json1.equals(json2)
    }

    String getString(){
        return StringEscapeUtils.escapeJava(toString())
    }

}

src/webcrawler/grails-app/domain/model/v2/bidding/TechSpecItem.groovy
package model.v2.bidding

import groovy.json.StringEscapeUtils
import groovy.transform.ToString
import util.domain.BaseDomain
import util.domain.DomainInterface

@ToString(includeNames = true, includeFields = true, excludes = "id,version,techSpec")
class TechSpecItem implements DomainInterface<TechSpecItem>{

    String title
    String typeValue

    static belongsTo = [techSpec: TechSpec]

    static hasMany = [values: TechSpecItemLevel2]

    static mapping = {
        values lazy: false
    }

    static constraints = {
        typeValue nullable: true
        title nullable: true
    }

    boolean compare(TechSpecItem other) {
        String json1 = getString()
        String json2 = other.getString()

        boolean valuesEquals = BaseDomain.compare2List(values, other.values)

        return json1.equals(json2) && valuesEquals
    }

    String getString(){
        return StringEscapeUtils.escapeJava(toString())
    }
}

src/webcrawler/grails-app/controllers/model/v2/BiddingController.groovy
package model.v2

import grails.converters.JSON
import grails.plugin.springsecurity.annotation.Secured
import grails.transaction.Transactional
import model.Role
import model.SysUser
import model.SysUserRole
import model.v2.bidding.Bidding

import static org.springframework.http.HttpStatus.NOT_FOUND

@Transactional(readOnly = true)
class BiddingController {

    def scrapService
    def springSecurityService
    def myMailProviderService

    static allowedMethods = [save: "POST", update: "PUT", delete: "DELETE"]

    @Secured("permitAll")
    def showPublic(Bidding biddingV2Instance) {

        if(springSecurityService.isLoggedIn()){
            redirect(action: 'show', id: biddingV2Instance.id)
        }else{
            respond biddingV2Instance
        }

    }

    @Secured(["ROLE_ADMIN", "ROLE_USER"])
    def index(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        params.offset = params.offset ?: 0

        def categoryID = params.id
        def category = categoryID ? Category.get(categoryID) : null

        def criteria = Bidding.createCriteria()
        def query = criteria.list {
            if (category) {
                eq("category", category)
            }
            order("dateCreated", "desc")
            maxResults(new Integer(params.max))
            firstResult(new Integer(params.offset))
        }

        def queryCount = Bidding.withCriteria {
            if (category) {
                eq("category", category)
            }
            order("dateCreated", "desc")
            projections {
                countDistinct "id"
            }
        }

        if (params.message)
            flash.error = params.message

        respond query, model: [totalCount: queryCount[0], categoryID: categoryID]
    }

    @Secured(["ROLE_ADMIN", "ROLE_USER"])
    def getByOtherContract(Integer max) {
        params.max = Math.min(max ?: 10, 100)
        params.offset = params.offset ?: 0

        def otherContractID = params.id
        def otherContract = otherContractID ? OtherContract.get(otherContractID) : null

        def criteria = Bidding.createCriteria()
        def query = criteria.list {
            if (otherContract) {
                eq("otherContract", otherContract)
            }
            order("dateCreated", "desc")
            maxResults(new Integer(params.max))
            firstResult(new Integer(params.offset))
        }

        def queryCount = Bidding.withCriteria {
            if (otherContract) {
                eq("otherContract", otherContract)
            }
            order("dateCreated", "desc")
            projections {
                countDistinct "id"
            }
        }

        if (params.message)
            flash.error = params.message

        respond query, model: [totalCount: queryCount[0], otherContractID: otherContractID]
    }

    @Secured(["ROLE_ADMIN", "ROLE_USER"])
    def show(Bidding biddingV2Instance) {
        respond biddingV2Instance
    }

    @Secured(["ROLE_ADMIN", "ROLE_USER"])
    def search(Integer max, Integer offset, String q) {
        params.max = Math.min(max ?: 10, 100)
        params.offset = offset ?: 0
        def query = new ArrayList()
        if (q) {
            def str = "%" + q + "%"
            def criteria = Bidding.createCriteria()
            query = criteria.list {

                or {
                    ilike('descripcion', str)
                    ilike('numero', str)
                }

                maxResults(params.max)
                firstResult(params.offset)
                order("dateCreated", "desc")
            }

            def queryTotal = Bidding.withCriteria {
                or {
                    ilike('descripcion', str)
                    ilike('numero', str)
                }
                projections {
                    countDistinct "id"
                }
            }

            if (queryTotal[0] == 0) {
                flash.error = "No results Found for your search criteria"
            }
            respond query, model: [totalCount: queryTotal[0], q: q]
        } else {
            respond query, model: [totalCount: 0]
        }

    }

    @Secured(["ROLE_ADMIN", "ROLE_USER"])
    def watchlist(Integer max, Integer offset) {
        params.max = Math.min(max ?: 10, 100)
        params.offset = offset ?: 0

        def query = new ArrayList()
        def criteria = Bidding.createCriteria()
        query = criteria.list {
            eq('observada', true)
            maxResults(params.max)
            firstResult(params.offset)
            order("dateCreated", "desc")
        }

        def queryTotal = Bidding.withCriteria {
            eq('observada', true)
            projections {
                countDistinct "id"
            }
        }

        respond query, model: [totalCount: queryTotal[0]]
    }

    @Secured("ROLE_ADMIN")
    @Transactional
    def migration1() {
        render scrapService.migrateWatchlist() as JSON
    }

//    @Secured("ROLE_ADMIN")
//    @Transactional
//    def debug1() {
//        // 2021-0-12-0-08-CL-033358
//        def contract = OtherContract.findByName("Mesa Conjunta MINSA-CSS")
//        def bid = scrapService.fetchListDependenciasByContract(contract, "2021-2-78-0-08-PE-013600")
//        println(bid)
//        Bidding.withTransaction {
//            bid.saveValidation()
//        }
//        render bid as JSON
//    }
//
//    @Secured("ROLE_ADMIN")
//    @Transactional
//    def debug2() {
//        // 2021-0-12-0-08-CL-033358
//        List bidUpdates = []
//        def contract = OtherContract.findByName("Mesa Conjunta MINSA-CSS")
//        def bidLocal = Bidding.findByNumero("2021-0-12-0-08-CL-033358")
//        def biddingUpdated = scrapService.fetchListDependenciasByContract(contract, "2021-0-12-0-08-CL-033358")
//        println(biddingUpdated)
//        if (biddingUpdated) {
//            if (bidLocal.isModelChanged(biddingUpdated)) {
//                bidUpdates << bidLocal
//            }
//        }
//
//        if (bidUpdates.size() > 0) {
////            myMailProviderService.watchListAlert(bidUpdates)
//            bidUpdates.each {
//                println("Updating Watchlist Bidding >>>>>>> " + it.numero)
//            }
//        }
//
//        render bidUpdates as JSON
//    }


//    @Secured("ROLE_ADMIN")
//    @Transactional
//    def migration2() {
//        render scrapService.migrateAlert() as JSON
//    }
//
//    @Secured("ROLE_ADMIN")
//    @Transactional
//    def migration3() {
//        render scrapService.migrateCleanWatchlist() as JSON
//    }

    @Secured("ROLE_ADMIN")
    @Transactional
    def migration4() {
        def userAuthority = Role.findByAuthority("ROLE_USER")
        def user = new SysUser()
        user.username = 'licitaciones1@lacomedicalgroup.com'
        user.password = 'lancotender2021'
        user.save(flush: true)
        SysUserRole.create(user, userAuthority, true)

        render user as JSON
    }

    @Secured("ROLE_ADMIN")
    @Transactional
    def testEmail() {
        myMailProviderService.reportEvent("Testing EMail")
        render "Success"
    }

    @Secured(["ROLE_ADMIN", "ROLE_USER"])
    @Transactional
    def toggleWatch(Integer id) {
        Bidding bidding = Bidding.get(id)
        if (bidding) {
            bidding.observada = !bidding.observada
            bidding.save(flush: true)
        }
        redirect(action: "show", id: id)
    }

    @Secured(["ROLE_ADMIN", "ROLE_USER"])
    protected void notFound() {
        request.withFormat  {
            form multipartForm {
                flash.message = message(code: 'default.not.found.message', args: [message(code: 'biddingV2.label', default: 'Bidding'), params.id])
                redirect action: "index", method: "GET"
            }
            '*' { render status: NOT_FOUND }
        }
    }

}

src/webcrawler/grails-app/views/bidding/_bidding.gsp
<div class="card">
    <div class="card-header">
        <i class="fa fa-align-justify"></i> <b>Licitacion</b>
        <g:if test="${displayWatch}">

            <g:if test="${!biddingInstance.observada}">
                    <a href="${createLink(controller: 'bidding', action: 'toggleWatch', id: biddingInstance.id)}" class="btn btn-primary pull-right"><i
                            class="icon-eyeglass"></i> Add to WatchList </a>
                </g:if>
                <g:else>
                    <a href="${createLink(controller: 'bidding', action: 'toggleWatch', id: biddingInstance.id)}" class="btn btn-danger pull-right"><i
                            class="icon-eyeglass"></i> Remove from WatchList </a>

                </g:else>
        </g:if>
    </div>

    <div class="card-body">
        <div id="show-bidding" class="content scaffold-show" role="main">
            <g:if test="${flash.message}">
                <div class="message" role="status">${flash.message}</div>
            </g:if>
            <ol class="property-list bidding">

                <g:if test="${biddingInstance?.numero}">
                    <li class="fieldcontain">
                        <span id="numero-label" class="property-label"><g:message code="bidding.numero.label"
                                                                                  default="Numero"/></span>

                        <span class="property-value" aria-labelledby="numero-label">
                            <a href="${biddingInstance.getPanamaLink()}">${biddingInstance.numero}</a>
                        </span>

                    </li>
                </g:if>

                <g:if test="${biddingInstance?.category}">
                    <li class="fieldcontain">
                        <span id="category-label" class="property-label"><g:message
                                code="bidding.category.label"
                                default="Category"/></span>

                        <span class="property-value" aria-labelledby="category-label">
                            ${biddingInstance?.category?.nivel1.encodeAsHTML()}
                        </span>

                    </li>
                </g:if>

                <g:if test="${biddingInstance?.contactUserCargo}">
                    <li class="fieldcontain">
                        <span id="contactUserCargo-label" class="property-label"><g:message
                                code="bidding.contactUserCargo.label" default="Contact User Cargo"/></span>

                        <span class="property-value" aria-labelledby="contactUserCargo-label"><g:fieldValue
                                bean="${biddingInstance}" field="contactUserCargo"/></span>

                    </li>
                </g:if>

                <g:if test="${biddingInstance?.contactUserNombre}">
                    <li class="fieldcontain">
                        <span id="contactUserNombre-label" class="property-label"><g:message
                                code="bidding.contactUserNombre.label" default="Contact User Nombre"/></span>

                        <span class="property-value" aria-labelledby="contactUserNombre-label"><g:fieldValue
                                bean="${biddingInstance}" field="contactUserNombre"/></span>

                    </li>
                </g:if>

                <g:if test="${biddingInstance?.dependencias}">
                    <li class="fieldcontain">
                        <span id="dependencias-label" class="property-label"><g:message
                                code="bidding.dependencias.label"
                                default="Dependencias"/></span>

                        <span class="property-value" aria-labelledby="dependencias-label"><g:fieldValue
                                bean="${biddingInstance}" field="dependencias"/></span>

                    </li>
                </g:if>

                <g:if test="${biddingInstance?.descripcion}">
                    <li class="fieldcontain">
                        <span id="descripcion-label" class="property-label"><g:message
                                code="bidding.descripcion.label"
                                default="Descripcion"/></span>

                        <span class="property-value" aria-labelledby="descripcion-label"><g:fieldValue
                                bean="${biddingInstance}"
                                field="descripcion"/></span>

                    </li>
                </g:if>

                <g:if test="${biddingInstance?.direccion}">
                    <li class="fieldcontain">
                        <span id="direccion-label" class="property-label"><g:message
                                code="bidding.direccion.label"
                                default="Direccion"/></span>

                        <span class="property-value" aria-labelledby="direccion-label"><g:fieldValue
                                bean="${biddingInstance}"
                                field="direccion"/></span>

                    </li>
                </g:if>

                <g:if test="${biddingInstance?.entidad}">
                    <li class="fieldcontain">
                        <span id="entidad-label" class="property-label"><g:message code="bidding.entidad.label"
                                                                                   default="Entidad"/></span>

                        <span class="property-value" aria-labelledby="entidad-label"><g:fieldValue
                                bean="${biddingInstance}"
                                field="entidad"/></span>

                    </li>
                </g:if>

                <g:if test="${biddingInstance?.objetoContratacion}">
                    <li class="fieldcontain">
                        <span id="objetoContratacion-label" class="property-label"><g:message
                                code="bidding.objetoContratacion.label" default="Objeto Contratacion"/></span>

                        <span class="property-value" aria-labelledby="objetoContratacion-label"><g:fieldValue
                                bean="${biddingInstance}" field="objetoContratacion"/></span>

                    </li>
                </g:if>

                <g:if test="${biddingInstance?.unidadDeCompra}">
                    <li class="fieldcontain">
                        <span id="unidadDeCompra-label" class="property-label"><g:message
                                code="bidding.unidadDeCompra.label"
                                default="Unidad De Compra"/></span>

                        <span class="property-value" aria-labelledby="unidadDeCompra-label"><g:fieldValue
                                bean="${biddingInstance}" field="unidadDeCompra"/></span>

                    </li>
                </g:if>

                <g:if test="${biddingInstance?.especificacionesTecnicas}">
                    <li class="fieldcontain">
                        <span id="especificacionesTecnicas-label" class="property-label"><g:message
                                code="bidding.especificacionesTecnicas.label"
                                default="Especificaciones Tecnicas"/></span>

                        <table class="table table-striped table-sm">
                            <thead>
                            <tr>
                                <th>Descripcion</th>
                                <th>Cantidad</th>
                                <th>Glosa</th>
                            </tr>
                            </thead>
                            <tbody>

                            <g:each in="${biddingInstance.especificacionesTecnicas.getAllItems()}" var="d">
                                <tr>
                                    <td>${d.descripcion}</td>
                                    <td>${d.cantidad}</td>
                                    <td>${d.glosa}</td>
                                </tr>
                            </g:each>
                            </tbody>
                        </table>

                    </li>
                </g:if>

                <g:if test="${biddingInstance?.documentosAdjuntos}">
                    <li class="fieldcontain">
                        <span id="documentosAdjuntos-label" class="property-label"><g:message
                                code="bidding.documentosAdjuntos.label" default="Documentos Adjuntos"/></span>

                        <table class="table table-striped table-sm">
                            <thead>
                            <tr>
                                <th>Comentario</th>
                                <th>Description</th>
                                <th>Fecha Creacion</th>
                            </tr>
                            </thead>
                            <tbody>
                            <g:each in="${biddingInstance.documentosAdjuntos}" var="d">
                                <tr>
                                    <td>${d.comentario}</td>
                                    <td>${d.description}</td>
                                    <td>${d.fechaCreacion}</td>
                                    <td>
                                        <a href="${util.UrlConstants.URL_BASE + d.link}">
                                            <i class="icon-cloud-download icons font-2xl d-block mt-4"></i>
                                        </a>
                                    </td>
                                </tr>
                            </g:each>
                            </tbody>
                        </table>
                    </li>
                </g:if>

                <g:if test="${biddingInstance?.avisos}">
                    <li class="fieldcontain">
                        <span id="avisos-label" class="property-label"><g:message code="bidding.avisos.label"
                                                                                  default="Avisos"/></span>

                        <table class="table table-striped table-sm">
                            <tbody>
                            <g:each in="${biddingInstance.avisos}" var="a">
                                <tr>
                                    <td>${a.label}</td>
                                    <td>${a.value_field}</td>
                                </tr>
                            </g:each>
                            </tbody>
                        </table>

                    </li>
                </g:if>

            </ol>
        </div>
    </div>
</div>

src/webcrawler/grails-app/views/bidding/_table.gsp
<table class="table table-striped">
    <thead>
    <tr>
        <th>Numero</th>
        <th>Descripcion</th>
        <th>Date Captured</th>
    </tr>
    </thead>
    <tbody>
    <g:each in="${biddingInstanceList}" var="entity">
        <tr>
            <td><a href="${createLink(controller: 'bidding', action: 'show', id: entity.id)}">${entity.numero}</a></td>
            <td>${entity.descripcion.size() > 20 ? entity.descripcion.substring(0,20) + " ..." : entity.descripcion}</td>
            <td><g:formatDate format="yyyy-MM-dd HH:mm a" date="${entity.dateCreated}"/></td>
        </tr>
    </g:each>
    </tbody>
</table>

src/webcrawler/grails-app/views/bidding/search.gsp
<%@ page import="model.v2.bidding.Bidding" %>
<!DOCTYPE html>
<html>
<head>
    <meta name="layout" content="admin">
    <g:set var="entityName" value="${message(code: 'bidding.label', default: 'Bidding')}"/>
    <title><g:message code="default.show.label" args="[entityName]"/></title>
</head>

<body>

<div class="row">
    <div class="col-lg-12">
        <div class="card">
            <div class="card-header">
                <strong>Busqueda</strong>
            </div>
            <div class="card-body">
                <g:form url='[controller: "bidding", action: "search"]' method="get" class="form-horizontal">
                        <div class="form-group row">
                            <div class="col-md-12">
                                <div class="input-group">
                                    <span class="input-group-btn">
                                        <button type="submit" class="btn btn-primary"><i class="fa fa-search"></i></button>
                                    </span>
                                    <input value="${params.q}" type="text" id="input1-group2" name="q" class="form-control" placeholder="Type your search ...">
                            </div>
                        </div>
                    </div>
                </g:form>
                <g:if test="${flash.message}">
                    <div class="message" role="status">${flash.message}</div>
                </g:if>
                <table class="table table-striped">
                    <thead>
                    <tr>
                        <th>Numero</th>
                        <th>Descripcion</th>
                        <th>Date Captured</th>
                    </tr>
                    </thead>
                    <tbody>
                    <g:each in="${biddingInstanceList}" var="entity">
                        <tr>
                            <td><a href="${createLink(controller: 'bidding', action: 'show', id: entity.id)}">${entity.numero}</a></td>
                            <td>${entity.descripcion.size() > 20 ? entity.descripcion.substring(0,20) + " ..." : entity.descripcion}</td>
                            <td><g:formatDate format="yyyy-MM-dd HH:mm a" date="${entity.dateCreated}"/></td>
                        </tr>
                    </g:each>
                    </tbody>
                </table>
                <div class="pagination">
                    <g:paginate total="${totalCount ?: 0}" params="${[q:params.q]}"/>
                </div>
            </div>
            <div class="card-footer">
            </div>
        </div>
    </div>
    <!--/.col-->
</div>
<!--/.row-->
</body>
</html>